---
name: Cloudproof KMS Javascript Library

on:
  workflow_call:
    inputs:
      subcommands:
        required: true
        type: string
      kms-version:
        required: true
        type: string

jobs:
  js-in-docker:
    runs-on: ubuntu-latest
    container: node:18.0.0

    services:
      kms:
        image: ghcr.io/cosmian/kms:${{ inputs.kms-version }}
        env:
          KMS_JWT_ISSUER_URI: https://kms-cosmian.eu.auth0.com/

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Cache build
        uses: actions/cache@v3
        with:
          path: |
            /github/home/.cache/puppeteer
            node_modules
            dist
            src/pkg
          key: ${{ runner.os }}-docker-node-${{ hashFiles('package.json') }}-${{ hashFiles('src/**', '!.git') }}
          restore-keys: |
            ${{ runner.os }}-docker-node-${{ hashFiles('package.json') }}-${{ hashFiles('src/**', '!.git') }}

      - name: Test
        run: ${{ inputs.subcommands }}
        env:
          KMS_HOST: kms
          AUTH0_TOKEN_1: ${{ secrets.AUTH0_TOKEN_1 }}
          AUTH0_TOKEN_2: ${{ secrets.AUTH0_TOKEN_2 }}
